### PR TITLE
Add betina quest article 

### PR DESCRIPTION
**Pull request by leo-martin**
+ add new iframe to play single track from bc (instead of album iframe)

### CODE REVIEW

**Comment by leo-martin** [comment]
https://blackbandcamp-article-bettina-quest-g5yujcfoqq-ew.a.run.app

**Comment by jcox-dev** [comment]
@leo-martin is this ready to be merged yet?

**Comment by leo-martin** [comment]
Hey @jcox-dev this needs to go online tomorrow morning. I've just added the latest changes (typo fixed) it should be OK for deploy

**Comment by leo-martin** [comment]
@jcox-dev you can merge and deploy (:

**Pull request merged**
